apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki
  - name: Tempo

datasources:
  # ── Prometheus ───────────────────────────────────────────────────────────────
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  # ── Loki ─────────────────────────────────────────────────────────────────────
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '(?:traceID|trace_id)=(\w+)'
          name: TraceID
          url: '$${__value.raw}'

  # ── Tempo ─────────────────────────────────────────────────────────────────────
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
      spanBar:
        type: Duration
      lokiSearch:
        datasourceUid: loki
