"""In-memory store for authenticated Grafana sessions.

Each session holds the Grafana URL, the browser-extracted session cookies, and
the datasource list discovered immediately after login.  The store is keyed by
an opaque ``session_id`` string generated by the frontend.

Note: This is an in-process store — it is cleared on restart and is not shared
across multiple backend replicas.  For multi-replica deployments, replace with
a Redis-backed implementation.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from datetime import UTC, datetime

import structlog

from src.models.responses import DatasourceInfo

logger = structlog.get_logger(__name__)


@dataclass
class GrafanaSession:
    """Everything the backend needs to proxy Grafana API calls for one user."""

    session_id: str
    grafana_url: str
    cookies: dict[str, str]
    datasources: list[DatasourceInfo]
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def cookie_header(self) -> str:
        """Return a ``Cookie:`` header value for httpx requests."""
        return "; ".join(f"{k}={v}" for k, v in self.cookies.items())


class SessionStore:
    """Thread-safe (asyncio) in-memory session store."""

    def __init__(self) -> None:
        self._sessions: dict[str, GrafanaSession] = {}
        self._lock = asyncio.Lock()

    async def put(self, session: GrafanaSession) -> None:
        async with self._lock:
            self._sessions[session.session_id] = session
        logger.info(
            "session_stored",
            session_id=session.session_id,
            datasource_count=len(session.datasources),
        )

    async def get(self, session_id: str) -> GrafanaSession | None:
        async with self._lock:
            return self._sessions.get(session_id)

    async def delete(self, session_id: str) -> None:
        async with self._lock:
            removed = self._sessions.pop(session_id, None)
        if removed:
            logger.info("session_deleted", session_id=session_id)

    def __len__(self) -> int:
        return len(self._sessions)


# Module-level singleton — injected via FastAPI Depends
_store = SessionStore()


def get_session_store() -> SessionStore:
    """FastAPI dependency that returns the singleton SessionStore."""
    return _store
